import sys
import argparse
from .emulator import Emulator
from .assembler import Assembler

def main():
    parser = argparse.ArgumentParser(prog='pythonRSC', description="An emulator for the RSC architecture written in Python.")
    parser.add_argument('mode', choices=["debug", "run", "assemble"])
    parser.add_argument('filein', help="your microcode file which contains instructions")
    parser.add_argument('-o', required="assemble" in sys.argv, help="the output file path for the assembler generated bytecode", type=str)
    parser.add_argument('-cfg', choices=["pdf", "png"], help="indicates if you want to see the control flow graph and its output type")
    parser.add_argument('-bn', help="indicates if you want to produce a binary ninja file format", action='store_true')
    args = parser.parse_args(sys.argv[1:])
    asm_obj = Assembler(args.filein)
    if args.o:
        if not args.bn:
            asm_obj.logisim_format(args.o)
        else:
            asm_obj.bn_format(args.o)
    else:
        debug_val = True if args.mode == "debug" else False
        emulator = Emulator(asm_obj, debug_val, args.cfg)
        emulator.start()

if __name__ == "__main__":
    main()